-- CineSense central evaluation table
-- Run this once in Supabase -> SQL Editor.

create table if not exists public.evaluation_responses (
  id bigint generated by default as identity primary key,
  response_id uuid not null unique,
  participant_id text not null,
  preferred_genre text not null,
  preferred_style text not null,
  preferred_age_restriction text not null,
  preferred_era text not null,
  selected_movie_id integer not null,
  selected_movie_title text not null,
  similarity_score integer,
  created_at timestamptz not null default now()
);

alter table public.evaluation_responses enable row level security;

-- Website visitors may INSERT a response, but cannot read, edit, or delete the dataset.
revoke all on table public.evaluation_responses from anon, authenticated;
grant insert on table public.evaluation_responses to anon, authenticated;

drop policy if exists "allow public evaluation inserts" on public.evaluation_responses;
create policy "allow public evaluation inserts"
on public.evaluation_responses
for insert
to anon, authenticated
with check (true);

-- No SELECT policy is created. View/export the full dataset while signed in to
-- your Supabase Dashboard instead of exposing respondents' data to site visitors.
